In [1]:
import numpy as np
var= np.array([9,8,7,6,5,4,3,2,1])
for i in var:
    print(i)

9
8
7
6
5
4
3
2
1


In [6]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [7]:
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)
            

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [8]:
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
for i in np.nditer(var3):
    print(i)
    

9
8
7
6
1
2
3
4


In [18]:
var4=np.array([[[9,8,7,6],[1,2,3,4]]])
print(var4)
for i in np.nditer(var4,flags=['buffered'],op_dtypes=["S"]):
    print(i)

    

[[[9 8 7 6]
  [1 2 3 4]]]
np.bytes_(b'9')
np.bytes_(b'8')
np.bytes_(b'7')
np.bytes_(b'6')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [19]:
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
for i,d in np.ndenumerate(var3):
    print(i,d)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
