# Putting contents of two or more arrays in a single array.


In [21]:
import numpy as np

var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([9, 8, 7, 6])

# Stacking along axis 1
a_new_axis1 = np.stack((var_1, var_2), axis=1)  # Stack along columns
print("Stacking along axis 1:")
print(a_new_axis1)

# Stacking along axis 0
a_new_axis0 = np.stack((var_1, var_2), axis=0)  # Stack along rows
print("\nStacking along axis 0:")
print(a_new_axis0)

# Horizontal stacking (equivalent to stacking along axis 1)
a_hstack = np.hstack((var_1, var_2))
print("\nHorizontal stacking (hstack):")
print(a_hstack)

# Vertical stacking (equivalent to stacking along axis 0)
a_vstack = np.vstack((var_1, var_2))
print("\nVertical stacking (vstack):")
print(a_vstack)

# Depth stacking (dstack) - this will create a 3D array
a_dstack = np.dstack((var_1, var_2))
print("\nDepth stacking (dstack):")
print(a_dstack)

Stacking along axis 1:
[[1 9]
 [2 8]
 [3 7]
 [4 6]]

Stacking along axis 0:
[[1 2 3 4]
 [9 8 7 6]]

Horizontal stacking (hstack):
[1 2 3 4 9 8 7 6]

Vertical stacking (vstack):
[[1 2 3 4]
 [9 8 7 6]]

Depth stacking (dstack):
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Overview of Split Functions


### Divide an array into multiple sub-arrays

## 1. Using np.split

In [23]:
import numpy as np

# Create a 1D array
arr1D = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal parts
split_arr1D = np.split(arr1D, 3)
print("1D Array Split into 3 Parts:")
print(split_arr1D)

# Create a 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the 2D array into 3 equal parts along axis 0 (rows)
split_arr2D_axis0 = np.split(arr2D, 3, axis=0)
print("\n2D Array Split into 3 Parts along Axis 0:")
print(split_arr2D_axis0)

# Split the 2D array into 3 equal parts along axis 1 (columns)
split_arr2D_axis1 = np.split(arr2D, 3, axis=1)
print("\n2D Array Split into 3 Parts along Axis 1:")
print(split_arr2D_axis1)

1D Array Split into 3 Parts:
[array([1, 2]), array([3, 4]), array([5, 6])]

2D Array Split into 3 Parts along Axis 0:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

2D Array Split into 3 Parts along Axis 1:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


## 2. Using np.hsplit

In [ ]:
# Create a 2D array
arr2D_h = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split the 2D array horizontally into 2 parts
h_split_arr2D = np.hsplit(arr2D_h, 2)
print("\nHorizontal Split of 2D Array:")
print(h_split_arr2D)

## 3. Using np.vsplit

In [ ]:
# Create a 2D array
arr2D_v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the 2D array vertically into 3 parts
v_split_arr2D = np.vsplit(arr2D_v, 3)
print("\nVertical Split of 2D Array:")
print(v_split_arr2D)

## 4. Using np.dsplit

In [ ]:
# Create a 3D array
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Split the 3D array along the third axis (depth)
d_split_arr3D = np.dsplit(arr3D, 2)
print("\nDepth Split of 3D Array:")
print(d_split_arr3D)