# Insert

In [11]:
import numpy as np
var=np.array([1,2,3,4,5])
v=np.insert(var,2,40)
v1=np.insert(var,(2,3),40) # Float value ko assign nhi karenga only integer value asiign ho skti hai
x=np.append(var,6.4)
print(v)
print(v1)
print(x)


[ 1  2 40  3  4  5]
[ 1  2 40  3 40  4  5]
[1.  2.  3.  4.  5.  6.4]


In [12]:
var1=np.array([[1,2,3],[4,5,6]])
v2=np.insert(var1,2,6,axis=1)
v3=np.insert(var1,2,6,axis=0)
v4=np.insert(var1,2,[22,33],axis=1)
v5=np.append(var1,[[44,55,66]],axis=0)
print(v2)
print()
print(v3)
print()
print(v4)
print()
print(v5)

[[1 2 6 3]
 [4 5 6 6]]

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[ 1  2 22  3]
 [ 4  5 33  6]]

[[ 1  2  3]
 [ 4  5  6]
 [44 55 66]]


# Delete

In [13]:
import numpy as np
var1=np.array([1,2,3,4,5])
print(var1)
d=np.delete(var1,2)
print(d)

[1 2 3 4 5]
[1 2 4 5]
