In [4]:
import numpy as np
var=np.matrix([[1,2],[4,5]])
var2=np.matrix([[2,3],[5,6]])
print(var)
print(type(var))
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [4 5]]
<class 'numpy.matrix'>
[[12 15]
 [33 42]]

[[12 15]
 [33 42]]


In [5]:
var1=np.array([[1,2,3],[4,5,6]])
var3=np.array([[1,2,3],[4,5,6]])
print(var1)
print(type(var1))
print(var3*var1)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[ 1  4  9]
 [16 25 36]]


# 1.Transpose

In [13]:
var1=np.array([[1,2,3],[4,5,6]])
print(var1)
print()
print(np.transpose(var1))
print("Shortcut:-")
print(var1.T)
print()
print(np.swapaxes(var1,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
Shortcut:-
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [15]:
var3=np.array([[1,2],[3,4]])
print(var3)
print()
print(np.swapaxes(var3,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [16]:
var4=np.array([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
var5=np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [ ]:
var6=np.matrix([[1,2],[3,4]])
print(var6)
print()
print(np.linalg.det(var5))