# Array

In [13]:
import numpy as np
x=[1,2,3,4,5,6]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim) # 1 to determine the dimension of array
y

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


array([1, 2, 3, 4, 5, 6])

In [10]:
l=[]
for i in range(1,5):
    x=int(eval(input('Enter :')))
    l.append(x)
print(np.array(l))
          

Enter : 4
Enter : 5
Enter : 6
Enter : 7


[4 5 6 7]


# Dimensions in Arrays
1-D,2-D,3-D and Higher dimension Arrays

In [15]:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar2)
print(ar2.ndim) # 2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [16]:
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
