In [ ]:
# Create NumPy Array Using Numpy Functions
# Spacial NumPy Array
# Array filled with 0's
# Array filled with 1's
# Create an empty array
# An array with a range of elements
# Array diagonal element filled with 1's
# Create an array with values that are spaced linearly in a apecified interval

In [2]:
 import numpy as np

# Array filled with 1's

In [ ]:
ar_zero =np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

# Array filled with 1's

In [17]:
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# Create an empty array


In [10]:
ar_em=np.empty((2,3))
print(ar_em)
# it will give values were already in memory at that location(previously memomry ka data a jata hai)

[[3.44900708e-307 4.22786102e-307 2.78145267e-307]
 [4.00537061e-307 9.45708167e-308 0.00000000e+000]]


# An array with a range of elements

In [12]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


# Array diagonal element filled with 1's

In [13]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
ar_dia1=np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Create an array with values that are spaced linearly in a a specified interval(linspace)


In [20]:
# evenly spaced values over a specified renage
# numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axix=0)
# num:(optional)no. of sample,default is 50

ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
