# Data type

In [2]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8])
print("Data Type: ",var.dtype)

Data Type:  int64


In [3]:
var=np.array([1.8,2.2,3.5,4.5])
print("Data Type: ",var.dtype)

Data Type:  float64


In [4]:
var=np.array(["a","a","d","f"])
print("Data Type: ",var.dtype) # string ka sign= <U1 

Data Type:  <U1


In [9]:
var=np.array(["d","r","g",1,2,3,4,5,6,7,8,])
print("Data Type: ",var.dtype)

Data Type:  <U21


In [14]:
x=np.array([1,2,3,4],dtype=np.int8)
print("Data Type : ",x.dtype)
print(x)

Data Type :  int8
[1 2 3 4]


In [15]:
x=np.array([1,2,3,4],dtype="f")
print("Data Type : ",x.dtype)
print(x)

Data Type :  float32
[1. 2. 3. 4.]


In [19]:
x2=np.array([1,2,3,4,8,9])
new=np.float32(x2)
print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print(x2)
print(new)

Data Type :  int64
Data Type :  float32
[1 2 3 4 8 9]
[1. 2. 3. 4. 8. 9.]


In [21]:
x2=np.array([1,2,3,4,8,9])
new=np.float32(x2)
new1=np.int_(new)
print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new1.dtype)
print(x2)
print(new)
print(new)

Data Type :  int64
Data Type :  float32
Data Type :  int64
[1 2 3 4 8 9]
[1. 2. 3. 4. 8. 9.]
[1. 2. 3. 4. 8. 9.]


In [22]:
x3=np.array([1,2,3,4,8,9])
new_1=x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4 8 9]
[1. 2. 3. 4. 8. 9.]
