# Indexing

In [1]:
import numpy as np
var=np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [2]:
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [3]:
var2=np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# Slicing

In [12]:
s=np.array([9,8,7,6,5,4,3])
print("2 to 5 : ",s[1:5])
print("2 to End :",s[1:])
print("start to 5: ",s[:5])
print("stop:",s[::2])
print("stop1:",s[1:6:2])

2 to 5 :  [8 7 6 5]
2 to End : [8 7 6 5 4 3]
start to 5:  [9 8 7 6 5]
stop: [9 7 5 3]
stop1: [8 6 4]


In [15]:
s1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(s1)
print("8 to 5:-",s1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
8 to 5:- [8 7 6 5]
